- hosts: localhost
  tasks:
  - name: Install docker.
    become: yes
    package:
      name: docker-ce
      state: present
  - name: Start docker service
    service:
      name: docker
      state: started
